[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[anonymous]
type=endpoint
context=lunara-test
allow=!all,ulaw,alaw
transport=transport-udp

[anonymous-identify]
type=identify
endpoint=anonymous
match=0.0.0.0/0
