/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnRouteImport } from './routes/sn'
import { Route as PmRouteImport } from './routes/pm'
import { Route as PeRouteImport } from './routes/pe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNumbersRouteImport } from './routes/_authenticated/numbers'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedDataResidencyRouteImport } from './routes/_authenticated/data-residency'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents.index'
import { Route as ApiAudioCallIdRouteImport } from './routes/api/audio.$callId'
import { Route as AuthenticatedCallsCallIdRouteImport } from './routes/_authenticated/calls.$callId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio/status'
import { Route as ApiPublicTwilioRecordingRouteImport } from './routes/api/public/twilio/recording'
import { Route as ApiPublicCrmCallsRouteImport } from './routes/api/public/crm/calls'

const SnRoute = SnRouteImport.update({
  id: '/sn',
  path: '/sn',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRoute = PmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const PeRoute = PeRouteImport.update({
  id: '/pe',
  path: '/pe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNumbersRoute = AuthenticatedNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataResidencyRoute =
  AuthenticatedDataResidencyRouteImport.update({
    id: '/data-residency',
    path: '/data-residency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const ApiAudioCallIdRoute = ApiAudioCallIdRouteImport.update({
  id: '/api/audio/$callId',
  path: '/api/audio/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallsCallIdRoute =
  AuthenticatedCallsCallIdRouteImport.update({
    id: '/$callId',
    path: '/$callId',
    getParentRoute: () => AuthenticatedCallsRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioRecordingRoute =
  ApiPublicTwilioRecordingRouteImport.update({
    id: '/api/public/twilio/recording',
    path: '/api/public/twilio/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrmCallsRoute = ApiPublicCrmCallsRouteImport.update({
  id: '/api/public/crm/calls',
  path: '/api/public/crm/calls',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pe': typeof PeRoute
  '/pm': typeof PmRoute
  '/sn': typeof SnRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calls': typeof AuthenticatedCallsRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-residency': typeof AuthenticatedDataResidencyRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/live': typeof AuthenticatedLiveRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/calls/$callId': typeof AuthenticatedCallsCallIdRoute
  '/api/audio/$callId': typeof ApiAudioCallIdRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/api/public/crm/calls': typeof ApiPublicCrmCallsRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pe': typeof PeRoute
  '/pm': typeof PmRoute
  '/sn': typeof SnRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calls': typeof AuthenticatedCallsRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-residency': typeof AuthenticatedDataResidencyRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/live': typeof AuthenticatedLiveRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/calls/$callId': typeof AuthenticatedCallsCallIdRoute
  '/api/audio/$callId': typeof ApiAudioCallIdRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/api/public/crm/calls': typeof ApiPublicCrmCallsRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pe': typeof PeRoute
  '/pm': typeof PmRoute
  '/sn': typeof SnRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRouteWithChildren
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-residency': typeof AuthenticatedDataResidencyRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/numbers': typeof AuthenticatedNumbersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/calls/$callId': typeof AuthenticatedCallsCallIdRoute
  '/api/audio/$callId': typeof ApiAudioCallIdRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/api/public/crm/calls': typeof ApiPublicCrmCallsRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pe'
    | '/pm'
    | '/sn'
    | '/agents'
    | '/analytics'
    | '/calls'
    | '/campaigns'
    | '/crm'
    | '/dashboard'
    | '/data-residency'
    | '/knowledge'
    | '/live'
    | '/numbers'
    | '/settings'
    | '/tools'
    | '/agents/$agentId'
    | '/calls/$callId'
    | '/api/audio/$callId'
    | '/agents/'
    | '/api/public/crm/calls'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pe'
    | '/pm'
    | '/sn'
    | '/analytics'
    | '/calls'
    | '/campaigns'
    | '/crm'
    | '/dashboard'
    | '/data-residency'
    | '/knowledge'
    | '/live'
    | '/numbers'
    | '/settings'
    | '/tools'
    | '/agents/$agentId'
    | '/calls/$callId'
    | '/api/audio/$callId'
    | '/agents'
    | '/api/public/crm/calls'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pe'
    | '/pm'
    | '/sn'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/calls'
    | '/_authenticated/campaigns'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-residency'
    | '/_authenticated/knowledge'
    | '/_authenticated/live'
    | '/_authenticated/numbers'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/calls/$callId'
    | '/api/audio/$callId'
    | '/_authenticated/agents/'
    | '/api/public/crm/calls'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PeRoute: typeof PeRoute
  PmRoute: typeof PmRoute
  SnRoute: typeof SnRoute
  ApiAudioCallIdRoute: typeof ApiAudioCallIdRoute
  ApiPublicCrmCallsRoute: typeof ApiPublicCrmCallsRoute
  ApiPublicTwilioRecordingRoute: typeof ApiPublicTwilioRecordingRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sn': {
      id: '/sn'
      path: '/sn'
      fullPath: '/sn'
      preLoaderRoute: typeof SnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pe': {
      id: '/pe'
      path: '/pe'
      fullPath: '/pe'
      preLoaderRoute: typeof PeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/numbers': {
      id: '/_authenticated/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AuthenticatedNumbersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-residency': {
      id: '/_authenticated/data-residency'
      path: '/data-residency'
      fullPath: '/data-residency'
      preLoaderRoute: typeof AuthenticatedDataResidencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/api/audio/$callId': {
      id: '/api/audio/$callId'
      path: '/api/audio/$callId'
      fullPath: '/api/audio/$callId'
      preLoaderRoute: typeof ApiAudioCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calls/$callId': {
      id: '/_authenticated/calls/$callId'
      path: '/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof AuthenticatedCallsCallIdRouteImport
      parentRoute: typeof AuthenticatedCallsRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/recording': {
      id: '/api/public/twilio/recording'
      path: '/api/public/twilio/recording'
      fullPath: '/api/public/twilio/recording'
      preLoaderRoute: typeof ApiPublicTwilioRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/calls': {
      id: '/api/public/crm/calls'
      path: '/api/public/crm/calls'
      fullPath: '/api/public/crm/calls'
      preLoaderRoute: typeof ApiPublicCrmCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedCallsRouteChildren {
  AuthenticatedCallsCallIdRoute: typeof AuthenticatedCallsCallIdRoute
}

const AuthenticatedCallsRouteChildren: AuthenticatedCallsRouteChildren = {
  AuthenticatedCallsCallIdRoute: AuthenticatedCallsCallIdRoute,
}

const AuthenticatedCallsRouteWithChildren =
  AuthenticatedCallsRoute._addFileChildren(AuthenticatedCallsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRouteWithChildren
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataResidencyRoute: typeof AuthenticatedDataResidencyRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedNumbersRoute: typeof AuthenticatedNumbersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRouteWithChildren,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataResidencyRoute: AuthenticatedDataResidencyRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedNumbersRoute: AuthenticatedNumbersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PeRoute: PeRoute,
  PmRoute: PmRoute,
  SnRoute: SnRoute,
  ApiAudioCallIdRoute: ApiAudioCallIdRoute,
  ApiPublicCrmCallsRoute: ApiPublicCrmCallsRoute,
  ApiPublicTwilioRecordingRoute: ApiPublicTwilioRecordingRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
