/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnRouteImport } from './routes/sn'
import { Route as PmRouteImport } from './routes/pm'
import { Route as PeRouteImport } from './routes/pe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNumbersRouteImport } from './routes/_authenticated/numbers'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedDataResidencyRouteImport } from './routes/_authenticated/data-residency'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedCopilotIndexRouteImport } from './routes/_authenticated/copilot.index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents.index'
import { Route as ApiAudioCallIdRouteImport } from './routes/api/audio.$callId'
import { Route as AuthenticatedCallsCallIdRouteImport } from './routes/_authenticated/calls.$callId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'
import { Route as AuthenticatedCopilotAgentsIndexRouteImport } from './routes/_authenticated/copilot.agents.index'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio/status'
import { Route as ApiPublicTwilioRecordingRouteImport } from './routes/api/public/twilio/recording'
import { Route as ApiPublicTwilioHandoffRouteImport } from './routes/api/public/twilio/handoff'
import { Route as ApiPublicTwilioCopilotTestTwimlRouteImport } from './routes/api/public/twilio/copilot-test-twiml'
import { Route as ApiPublicTwilioCopilotStreamRouteImport } from './routes/api/public/twilio/copilot-stream'
import { Route as ApiPublicJambonzStatusRouteImport } from './routes/api/public/jambonz/status'
import { Route as ApiPublicJambonzCallRouteImport } from './routes/api/public/jambonz/call'
import { Route as ApiPublicHooksTicketsRetryRouteImport } from './routes/api/public/hooks/tickets-retry'
import { Route as ApiPublicHooksSlaSnapshotRouteImport } from './routes/api/public/hooks/sla-snapshot'
import { Route as ApiPublicHooksPostCallVerificationRouteImport } from './routes/api/public/hooks/post-call-verification'
import { Route as ApiPublicHooksCrmHealthcheckRouteImport } from './routes/api/public/hooks/crm-healthcheck'
import { Route as ApiPublicCrmTicketUpdateRouteImport } from './routes/api/public/crm/ticket-update'
import { Route as ApiPublicCrmSandboxRouteImport } from './routes/api/public/crm/sandbox'
import { Route as ApiPublicCrmCallsRouteImport } from './routes/api/public/crm/calls'
import { Route as AuthenticatedCopilotSessionsSessionIdRouteImport } from './routes/_authenticated/copilot.sessions.$sessionId'
import { Route as AuthenticatedCopilotAgentsAgentIdRouteImport } from './routes/_authenticated/copilot.agents.$agentId'
import { Route as ApiPublicTelegramWebhookAgentIdRouteImport } from './routes/api/public/telegram/webhook.$agentId'

const SnRoute = SnRouteImport.update({
  id: '/sn',
  path: '/sn',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRoute = PmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const PeRoute = PeRouteImport.update({
  id: '/pe',
  path: '/pe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNumbersRoute = AuthenticatedNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataResidencyRoute =
  AuthenticatedDataResidencyRouteImport.update({
    id: '/data-residency',
    path: '/data-residency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotIndexRoute =
  AuthenticatedCopilotIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCopilotRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const ApiAudioCallIdRoute = ApiAudioCallIdRouteImport.update({
  id: '/api/audio/$callId',
  path: '/api/audio/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallsCallIdRoute =
  AuthenticatedCallsCallIdRouteImport.update({
    id: '/$callId',
    path: '/$callId',
    getParentRoute: () => AuthenticatedCallsRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const AuthenticatedCopilotAgentsIndexRoute =
  AuthenticatedCopilotAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedCopilotRoute,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioRecordingRoute =
  ApiPublicTwilioRecordingRouteImport.update({
    id: '/api/public/twilio/recording',
    path: '/api/public/twilio/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioHandoffRoute = ApiPublicTwilioHandoffRouteImport.update({
  id: '/api/public/twilio/handoff',
  path: '/api/public/twilio/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioCopilotTestTwimlRoute =
  ApiPublicTwilioCopilotTestTwimlRouteImport.update({
    id: '/api/public/twilio/copilot-test-twiml',
    path: '/api/public/twilio/copilot-test-twiml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioCopilotStreamRoute =
  ApiPublicTwilioCopilotStreamRouteImport.update({
    id: '/api/public/twilio/copilot-stream',
    path: '/api/public/twilio/copilot-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJambonzStatusRoute = ApiPublicJambonzStatusRouteImport.update({
  id: '/api/public/jambonz/status',
  path: '/api/public/jambonz/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJambonzCallRoute = ApiPublicJambonzCallRouteImport.update({
  id: '/api/public/jambonz/call',
  path: '/api/public/jambonz/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTicketsRetryRoute =
  ApiPublicHooksTicketsRetryRouteImport.update({
    id: '/api/public/hooks/tickets-retry',
    path: '/api/public/hooks/tickets-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSlaSnapshotRoute =
  ApiPublicHooksSlaSnapshotRouteImport.update({
    id: '/api/public/hooks/sla-snapshot',
    path: '/api/public/hooks/sla-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPostCallVerificationRoute =
  ApiPublicHooksPostCallVerificationRouteImport.update({
    id: '/api/public/hooks/post-call-verification',
    path: '/api/public/hooks/post-call-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmHealthcheckRoute =
  ApiPublicHooksCrmHealthcheckRouteImport.update({
    id: '/api/public/hooks/crm-healthcheck',
    path: '/api/public/hooks/crm-healthcheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrmTicketUpdateRoute =
  ApiPublicCrmTicketUpdateRouteImport.update({
    id: '/api/public/crm/ticket-update',
    path: '/api/public/crm/ticket-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrmSandboxRoute = ApiPublicCrmSandboxRouteImport.update({
  id: '/api/public/crm/sandbox',
  path: '/api/public/crm/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmCallsRoute = ApiPublicCrmCallsRouteImport.update({
  id: '/api/public/crm/calls',
  path: '/api/public/crm/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCopilotSessionsSessionIdRoute =
  AuthenticatedCopilotSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedCopilotRoute,
  } as any)
const AuthenticatedCopilotAgentsAgentIdRoute =
  AuthenticatedCopilotAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedCopilotRoute,
  } as any)
const ApiPublicTelegramWebhookAgentIdRoute =
  ApiPublicTelegramWebhookAgentIdRouteImport.update({
    id: '/api/public/telegram/webhook/$agentId',
    path: '/api/public/telegram/webhook/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pe': typeof PeRoute
  '/pm': typeof PmRoute
  '/sn': typeof SnRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calls': typeof AuthenticatedCallsRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/copilot': typeof AuthenticatedCopilotRouteWithChildren
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-residency': typeof AuthenticatedDataResidencyRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/live': typeof AuthenticatedLiveRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/calls/$callId': typeof AuthenticatedCallsCallIdRoute
  '/api/audio/$callId': typeof ApiAudioCallIdRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/copilot/agents/$agentId': typeof AuthenticatedCopilotAgentsAgentIdRoute
  '/copilot/sessions/$sessionId': typeof AuthenticatedCopilotSessionsSessionIdRoute
  '/api/public/crm/calls': typeof ApiPublicCrmCallsRoute
  '/api/public/crm/sandbox': typeof ApiPublicCrmSandboxRoute
  '/api/public/crm/ticket-update': typeof ApiPublicCrmTicketUpdateRoute
  '/api/public/hooks/crm-healthcheck': typeof ApiPublicHooksCrmHealthcheckRoute
  '/api/public/hooks/post-call-verification': typeof ApiPublicHooksPostCallVerificationRoute
  '/api/public/hooks/sla-snapshot': typeof ApiPublicHooksSlaSnapshotRoute
  '/api/public/hooks/tickets-retry': typeof ApiPublicHooksTicketsRetryRoute
  '/api/public/jambonz/call': typeof ApiPublicJambonzCallRoute
  '/api/public/jambonz/status': typeof ApiPublicJambonzStatusRoute
  '/api/public/twilio/copilot-stream': typeof ApiPublicTwilioCopilotStreamRoute
  '/api/public/twilio/copilot-test-twiml': typeof ApiPublicTwilioCopilotTestTwimlRoute
  '/api/public/twilio/handoff': typeof ApiPublicTwilioHandoffRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/copilot/agents/': typeof AuthenticatedCopilotAgentsIndexRoute
  '/api/public/telegram/webhook/$agentId': typeof ApiPublicTelegramWebhookAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pe': typeof PeRoute
  '/pm': typeof PmRoute
  '/sn': typeof SnRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calls': typeof AuthenticatedCallsRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-residency': typeof AuthenticatedDataResidencyRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/live': typeof AuthenticatedLiveRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/calls/$callId': typeof AuthenticatedCallsCallIdRoute
  '/api/audio/$callId': typeof ApiAudioCallIdRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/copilot': typeof AuthenticatedCopilotIndexRoute
  '/copilot/agents/$agentId': typeof AuthenticatedCopilotAgentsAgentIdRoute
  '/copilot/sessions/$sessionId': typeof AuthenticatedCopilotSessionsSessionIdRoute
  '/api/public/crm/calls': typeof ApiPublicCrmCallsRoute
  '/api/public/crm/sandbox': typeof ApiPublicCrmSandboxRoute
  '/api/public/crm/ticket-update': typeof ApiPublicCrmTicketUpdateRoute
  '/api/public/hooks/crm-healthcheck': typeof ApiPublicHooksCrmHealthcheckRoute
  '/api/public/hooks/post-call-verification': typeof ApiPublicHooksPostCallVerificationRoute
  '/api/public/hooks/sla-snapshot': typeof ApiPublicHooksSlaSnapshotRoute
  '/api/public/hooks/tickets-retry': typeof ApiPublicHooksTicketsRetryRoute
  '/api/public/jambonz/call': typeof ApiPublicJambonzCallRoute
  '/api/public/jambonz/status': typeof ApiPublicJambonzStatusRoute
  '/api/public/twilio/copilot-stream': typeof ApiPublicTwilioCopilotStreamRoute
  '/api/public/twilio/copilot-test-twiml': typeof ApiPublicTwilioCopilotTestTwimlRoute
  '/api/public/twilio/handoff': typeof ApiPublicTwilioHandoffRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/copilot/agents': typeof AuthenticatedCopilotAgentsIndexRoute
  '/api/public/telegram/webhook/$agentId': typeof ApiPublicTelegramWebhookAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pe': typeof PeRoute
  '/pm': typeof PmRoute
  '/sn': typeof SnRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRouteWithChildren
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-residency': typeof AuthenticatedDataResidencyRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/numbers': typeof AuthenticatedNumbersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/calls/$callId': typeof AuthenticatedCallsCallIdRoute
  '/api/audio/$callId': typeof ApiAudioCallIdRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/_authenticated/copilot/agents/$agentId': typeof AuthenticatedCopilotAgentsAgentIdRoute
  '/_authenticated/copilot/sessions/$sessionId': typeof AuthenticatedCopilotSessionsSessionIdRoute
  '/api/public/crm/calls': typeof ApiPublicCrmCallsRoute
  '/api/public/crm/sandbox': typeof ApiPublicCrmSandboxRoute
  '/api/public/crm/ticket-update': typeof ApiPublicCrmTicketUpdateRoute
  '/api/public/hooks/crm-healthcheck': typeof ApiPublicHooksCrmHealthcheckRoute
  '/api/public/hooks/post-call-verification': typeof ApiPublicHooksPostCallVerificationRoute
  '/api/public/hooks/sla-snapshot': typeof ApiPublicHooksSlaSnapshotRoute
  '/api/public/hooks/tickets-retry': typeof ApiPublicHooksTicketsRetryRoute
  '/api/public/jambonz/call': typeof ApiPublicJambonzCallRoute
  '/api/public/jambonz/status': typeof ApiPublicJambonzStatusRoute
  '/api/public/twilio/copilot-stream': typeof ApiPublicTwilioCopilotStreamRoute
  '/api/public/twilio/copilot-test-twiml': typeof ApiPublicTwilioCopilotTestTwimlRoute
  '/api/public/twilio/handoff': typeof ApiPublicTwilioHandoffRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/_authenticated/copilot/agents/': typeof AuthenticatedCopilotAgentsIndexRoute
  '/api/public/telegram/webhook/$agentId': typeof ApiPublicTelegramWebhookAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pe'
    | '/pm'
    | '/sn'
    | '/agents'
    | '/analytics'
    | '/calls'
    | '/campaigns'
    | '/copilot'
    | '/crm'
    | '/dashboard'
    | '/data-residency'
    | '/knowledge'
    | '/live'
    | '/numbers'
    | '/settings'
    | '/tickets'
    | '/tools'
    | '/agents/$agentId'
    | '/calls/$callId'
    | '/api/audio/$callId'
    | '/agents/'
    | '/copilot/'
    | '/copilot/agents/$agentId'
    | '/copilot/sessions/$sessionId'
    | '/api/public/crm/calls'
    | '/api/public/crm/sandbox'
    | '/api/public/crm/ticket-update'
    | '/api/public/hooks/crm-healthcheck'
    | '/api/public/hooks/post-call-verification'
    | '/api/public/hooks/sla-snapshot'
    | '/api/public/hooks/tickets-retry'
    | '/api/public/jambonz/call'
    | '/api/public/jambonz/status'
    | '/api/public/twilio/copilot-stream'
    | '/api/public/twilio/copilot-test-twiml'
    | '/api/public/twilio/handoff'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
    | '/copilot/agents/'
    | '/api/public/telegram/webhook/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pe'
    | '/pm'
    | '/sn'
    | '/analytics'
    | '/calls'
    | '/campaigns'
    | '/crm'
    | '/dashboard'
    | '/data-residency'
    | '/knowledge'
    | '/live'
    | '/numbers'
    | '/settings'
    | '/tickets'
    | '/tools'
    | '/agents/$agentId'
    | '/calls/$callId'
    | '/api/audio/$callId'
    | '/agents'
    | '/copilot'
    | '/copilot/agents/$agentId'
    | '/copilot/sessions/$sessionId'
    | '/api/public/crm/calls'
    | '/api/public/crm/sandbox'
    | '/api/public/crm/ticket-update'
    | '/api/public/hooks/crm-healthcheck'
    | '/api/public/hooks/post-call-verification'
    | '/api/public/hooks/sla-snapshot'
    | '/api/public/hooks/tickets-retry'
    | '/api/public/jambonz/call'
    | '/api/public/jambonz/status'
    | '/api/public/twilio/copilot-stream'
    | '/api/public/twilio/copilot-test-twiml'
    | '/api/public/twilio/handoff'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
    | '/copilot/agents'
    | '/api/public/telegram/webhook/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pe'
    | '/pm'
    | '/sn'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/calls'
    | '/_authenticated/campaigns'
    | '/_authenticated/copilot'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-residency'
    | '/_authenticated/knowledge'
    | '/_authenticated/live'
    | '/_authenticated/numbers'
    | '/_authenticated/settings'
    | '/_authenticated/tickets'
    | '/_authenticated/tools'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/calls/$callId'
    | '/api/audio/$callId'
    | '/_authenticated/agents/'
    | '/_authenticated/copilot/'
    | '/_authenticated/copilot/agents/$agentId'
    | '/_authenticated/copilot/sessions/$sessionId'
    | '/api/public/crm/calls'
    | '/api/public/crm/sandbox'
    | '/api/public/crm/ticket-update'
    | '/api/public/hooks/crm-healthcheck'
    | '/api/public/hooks/post-call-verification'
    | '/api/public/hooks/sla-snapshot'
    | '/api/public/hooks/tickets-retry'
    | '/api/public/jambonz/call'
    | '/api/public/jambonz/status'
    | '/api/public/twilio/copilot-stream'
    | '/api/public/twilio/copilot-test-twiml'
    | '/api/public/twilio/handoff'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
    | '/_authenticated/copilot/agents/'
    | '/api/public/telegram/webhook/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PeRoute: typeof PeRoute
  PmRoute: typeof PmRoute
  SnRoute: typeof SnRoute
  ApiAudioCallIdRoute: typeof ApiAudioCallIdRoute
  ApiPublicCrmCallsRoute: typeof ApiPublicCrmCallsRoute
  ApiPublicCrmSandboxRoute: typeof ApiPublicCrmSandboxRoute
  ApiPublicCrmTicketUpdateRoute: typeof ApiPublicCrmTicketUpdateRoute
  ApiPublicHooksCrmHealthcheckRoute: typeof ApiPublicHooksCrmHealthcheckRoute
  ApiPublicHooksPostCallVerificationRoute: typeof ApiPublicHooksPostCallVerificationRoute
  ApiPublicHooksSlaSnapshotRoute: typeof ApiPublicHooksSlaSnapshotRoute
  ApiPublicHooksTicketsRetryRoute: typeof ApiPublicHooksTicketsRetryRoute
  ApiPublicJambonzCallRoute: typeof ApiPublicJambonzCallRoute
  ApiPublicJambonzStatusRoute: typeof ApiPublicJambonzStatusRoute
  ApiPublicTwilioCopilotStreamRoute: typeof ApiPublicTwilioCopilotStreamRoute
  ApiPublicTwilioCopilotTestTwimlRoute: typeof ApiPublicTwilioCopilotTestTwimlRoute
  ApiPublicTwilioHandoffRoute: typeof ApiPublicTwilioHandoffRoute
  ApiPublicTwilioRecordingRoute: typeof ApiPublicTwilioRecordingRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
  ApiPublicTelegramWebhookAgentIdRoute: typeof ApiPublicTelegramWebhookAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sn': {
      id: '/sn'
      path: '/sn'
      fullPath: '/sn'
      preLoaderRoute: typeof SnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pe': {
      id: '/pe'
      path: '/pe'
      fullPath: '/pe'
      preLoaderRoute: typeof PeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/numbers': {
      id: '/_authenticated/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AuthenticatedNumbersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-residency': {
      id: '/_authenticated/data-residency'
      path: '/data-residency'
      fullPath: '/data-residency'
      preLoaderRoute: typeof AuthenticatedDataResidencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copilot/': {
      id: '/_authenticated/copilot/'
      path: '/'
      fullPath: '/copilot/'
      preLoaderRoute: typeof AuthenticatedCopilotIndexRouteImport
      parentRoute: typeof AuthenticatedCopilotRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/api/audio/$callId': {
      id: '/api/audio/$callId'
      path: '/api/audio/$callId'
      fullPath: '/api/audio/$callId'
      preLoaderRoute: typeof ApiAudioCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calls/$callId': {
      id: '/_authenticated/calls/$callId'
      path: '/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof AuthenticatedCallsCallIdRouteImport
      parentRoute: typeof AuthenticatedCallsRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/copilot/agents/': {
      id: '/_authenticated/copilot/agents/'
      path: '/agents'
      fullPath: '/copilot/agents/'
      preLoaderRoute: typeof AuthenticatedCopilotAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedCopilotRoute
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/recording': {
      id: '/api/public/twilio/recording'
      path: '/api/public/twilio/recording'
      fullPath: '/api/public/twilio/recording'
      preLoaderRoute: typeof ApiPublicTwilioRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/handoff': {
      id: '/api/public/twilio/handoff'
      path: '/api/public/twilio/handoff'
      fullPath: '/api/public/twilio/handoff'
      preLoaderRoute: typeof ApiPublicTwilioHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/copilot-test-twiml': {
      id: '/api/public/twilio/copilot-test-twiml'
      path: '/api/public/twilio/copilot-test-twiml'
      fullPath: '/api/public/twilio/copilot-test-twiml'
      preLoaderRoute: typeof ApiPublicTwilioCopilotTestTwimlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/copilot-stream': {
      id: '/api/public/twilio/copilot-stream'
      path: '/api/public/twilio/copilot-stream'
      fullPath: '/api/public/twilio/copilot-stream'
      preLoaderRoute: typeof ApiPublicTwilioCopilotStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jambonz/status': {
      id: '/api/public/jambonz/status'
      path: '/api/public/jambonz/status'
      fullPath: '/api/public/jambonz/status'
      preLoaderRoute: typeof ApiPublicJambonzStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jambonz/call': {
      id: '/api/public/jambonz/call'
      path: '/api/public/jambonz/call'
      fullPath: '/api/public/jambonz/call'
      preLoaderRoute: typeof ApiPublicJambonzCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tickets-retry': {
      id: '/api/public/hooks/tickets-retry'
      path: '/api/public/hooks/tickets-retry'
      fullPath: '/api/public/hooks/tickets-retry'
      preLoaderRoute: typeof ApiPublicHooksTicketsRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-snapshot': {
      id: '/api/public/hooks/sla-snapshot'
      path: '/api/public/hooks/sla-snapshot'
      fullPath: '/api/public/hooks/sla-snapshot'
      preLoaderRoute: typeof ApiPublicHooksSlaSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/post-call-verification': {
      id: '/api/public/hooks/post-call-verification'
      path: '/api/public/hooks/post-call-verification'
      fullPath: '/api/public/hooks/post-call-verification'
      preLoaderRoute: typeof ApiPublicHooksPostCallVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-healthcheck': {
      id: '/api/public/hooks/crm-healthcheck'
      path: '/api/public/hooks/crm-healthcheck'
      fullPath: '/api/public/hooks/crm-healthcheck'
      preLoaderRoute: typeof ApiPublicHooksCrmHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/ticket-update': {
      id: '/api/public/crm/ticket-update'
      path: '/api/public/crm/ticket-update'
      fullPath: '/api/public/crm/ticket-update'
      preLoaderRoute: typeof ApiPublicCrmTicketUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/sandbox': {
      id: '/api/public/crm/sandbox'
      path: '/api/public/crm/sandbox'
      fullPath: '/api/public/crm/sandbox'
      preLoaderRoute: typeof ApiPublicCrmSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/calls': {
      id: '/api/public/crm/calls'
      path: '/api/public/crm/calls'
      fullPath: '/api/public/crm/calls'
      preLoaderRoute: typeof ApiPublicCrmCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/copilot/sessions/$sessionId': {
      id: '/_authenticated/copilot/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/copilot/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedCopilotSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedCopilotRoute
    }
    '/_authenticated/copilot/agents/$agentId': {
      id: '/_authenticated/copilot/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/copilot/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedCopilotAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedCopilotRoute
    }
    '/api/public/telegram/webhook/$agentId': {
      id: '/api/public/telegram/webhook/$agentId'
      path: '/api/public/telegram/webhook/$agentId'
      fullPath: '/api/public/telegram/webhook/$agentId'
      preLoaderRoute: typeof ApiPublicTelegramWebhookAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedCallsRouteChildren {
  AuthenticatedCallsCallIdRoute: typeof AuthenticatedCallsCallIdRoute
}

const AuthenticatedCallsRouteChildren: AuthenticatedCallsRouteChildren = {
  AuthenticatedCallsCallIdRoute: AuthenticatedCallsCallIdRoute,
}

const AuthenticatedCallsRouteWithChildren =
  AuthenticatedCallsRoute._addFileChildren(AuthenticatedCallsRouteChildren)

interface AuthenticatedCopilotRouteChildren {
  AuthenticatedCopilotIndexRoute: typeof AuthenticatedCopilotIndexRoute
  AuthenticatedCopilotAgentsAgentIdRoute: typeof AuthenticatedCopilotAgentsAgentIdRoute
  AuthenticatedCopilotSessionsSessionIdRoute: typeof AuthenticatedCopilotSessionsSessionIdRoute
  AuthenticatedCopilotAgentsIndexRoute: typeof AuthenticatedCopilotAgentsIndexRoute
}

const AuthenticatedCopilotRouteChildren: AuthenticatedCopilotRouteChildren = {
  AuthenticatedCopilotIndexRoute: AuthenticatedCopilotIndexRoute,
  AuthenticatedCopilotAgentsAgentIdRoute:
    AuthenticatedCopilotAgentsAgentIdRoute,
  AuthenticatedCopilotSessionsSessionIdRoute:
    AuthenticatedCopilotSessionsSessionIdRoute,
  AuthenticatedCopilotAgentsIndexRoute: AuthenticatedCopilotAgentsIndexRoute,
}

const AuthenticatedCopilotRouteWithChildren =
  AuthenticatedCopilotRoute._addFileChildren(AuthenticatedCopilotRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRouteWithChildren
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRouteWithChildren
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataResidencyRoute: typeof AuthenticatedDataResidencyRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedNumbersRoute: typeof AuthenticatedNumbersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRouteWithChildren,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRouteWithChildren,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataResidencyRoute: AuthenticatedDataResidencyRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedNumbersRoute: AuthenticatedNumbersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PeRoute: PeRoute,
  PmRoute: PmRoute,
  SnRoute: SnRoute,
  ApiAudioCallIdRoute: ApiAudioCallIdRoute,
  ApiPublicCrmCallsRoute: ApiPublicCrmCallsRoute,
  ApiPublicCrmSandboxRoute: ApiPublicCrmSandboxRoute,
  ApiPublicCrmTicketUpdateRoute: ApiPublicCrmTicketUpdateRoute,
  ApiPublicHooksCrmHealthcheckRoute: ApiPublicHooksCrmHealthcheckRoute,
  ApiPublicHooksPostCallVerificationRoute:
    ApiPublicHooksPostCallVerificationRoute,
  ApiPublicHooksSlaSnapshotRoute: ApiPublicHooksSlaSnapshotRoute,
  ApiPublicHooksTicketsRetryRoute: ApiPublicHooksTicketsRetryRoute,
  ApiPublicJambonzCallRoute: ApiPublicJambonzCallRoute,
  ApiPublicJambonzStatusRoute: ApiPublicJambonzStatusRoute,
  ApiPublicTwilioCopilotStreamRoute: ApiPublicTwilioCopilotStreamRoute,
  ApiPublicTwilioCopilotTestTwimlRoute: ApiPublicTwilioCopilotTestTwimlRoute,
  ApiPublicTwilioHandoffRoute: ApiPublicTwilioHandoffRoute,
  ApiPublicTwilioRecordingRoute: ApiPublicTwilioRecordingRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
  ApiPublicTelegramWebhookAgentIdRoute: ApiPublicTelegramWebhookAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
